### ISSUE TITLE
number_traces_max_t decreases (?)

### ISSUE THREAD

**Issue by matbok** [oreparaz/dudect#17]
As in the following image, I experience a strange behavior with the print of the variable number_traces_max_t:
![image](https://user-images.githubusercontent.com/72856962/118458470-14fb6b80-b6fb-11eb-9bf1-528693d607df.png)
is it normal that it sometimes decreases?

**Comment by oreparaz** [comment]
I agree this behavior seems super weird and at first sight misleading -  but it could happen in the following situation. Recall that code today does not do a _single_ t-test, but a bunch of them (simultaneously) for different choices of a pre-processing parameter (namely, a cropping threshold parameter). Not all t-test are performed on the exact same number of measurements, precisely because the pre-processing that happens throws some measurements away depending on the cropping value.

So in your case, it's likely that the third line (meas: 0.02M) corresponds to a different choice of the cropping threshold that happens to achieve a higher t-statistic with a lower number of measurements, compared to the pre-processing parameter that yielded the max value one line earlier. To see how this happens, I recommend dumping the index that maximizes the t-value (variable ret in the following function) https://github.com/oreparaz/dudect/blob/5e04163176b02194d8372a11a9a17a15ffb66327/src/dudect.h#L327 and check that such index changes sometimes from line to line.

A better way to surface this would be to output both the number of "unprocessed" measurements (which is strictly monotonic increasing, and today is not surfaced to the terminal output) and the number of "post-processed" measurements (the "meas" number that is surfaced today, which could "decrease" across lines as you noticed)

**Comment by matbok** [comment]
clear.
thank you for the detailed explanation.
So I close this because it's not an issue.
